### PR TITLE
test: useTransactor hook

### LINKED ISSUE #380: [TEST] Create unit tests for `useTransactor.ts`
## Issue Overview

Unit tests required for the indicated file to ease future refactoring and feature validations.

## Proposed Solutions or Ideas (more like tips and reminders)

- We use vitest to run the unit tests, can refer to their documentation for the syntax: https://vitest.dev/, Jest developers shouldn't have too much of a hard time getting used to the syntax.
- Note that hooks testing tools are also now imported via `@testing-library/react`,
- Please refer to `README.md` on how to execute the tests
- Use `it.only()` to isolate tests in case you need to, but do not forget to remove it once you are submitting your PR.
- Mock when necessary. please make sure that the tests *NOT ONLY* works on your device
- If you're not sure of the features of the code unit to test, please refer to the [documentation](https://docs.scaffoldstark.com/hooks/), or free to ask on this issue page or on the Telegram Group

## Code Coverage
*IMPORTANT* - When submitting a PR, please provide a screenshot of the coverage for the specific units you are working on. We would like to achieve >= 70 % code coverage. 

Happy Hacking!

Example: 
image

### PR DESCRIPTION
**Pull request by No-bodyq**
# Test useTransactor hook

Fixes #380 

## Types of change

- [x] Feature
- [ ] Bug
- [ ] Enhancement

### CODE REVIEW

**Review by Nadai2010 — CHANGES_REQUESTED** [review]
Thanks for your work, @No-bodyq! Let me know once it's completed.  

- Please run the command `yarn next:check-types` to identify the various errors in CI, as well as in your `useTransactor.test.ts` file.  
image

- Aim to improve the test coverage to 100%. Here's a snapshot for reference:  
  Coverage Report

**Comment by metalboyrick** [comment]
hey @No-bodyq don't forget to attach the coverage screenshot on the PR. not reaching 100% is fine!

**Review by metalboyrick — CHANGES_REQUESTED** [review]
please resolve the ABI issue raised by @Nadai2010 and it should be good

**Comment by No-bodyq** [comment]
{122D5C8E-F254-4C5C-AB48-54D0BF32444D}

Hello @metalboyrick CI is passing now, I think I've already fixed the issues. `yarn next: check types` doesn't return anymore errors on my end

**Review by metalboyrick — APPROVED** [review]
looks good on my end, thanks for the PR ! will let @Nadai2010 merge if it is all good from his side

**Review by Nadai2010 — APPROVED** [review]

**Pull request merged**
