### PR TITLE
UseScaffoldEventHistory.test

### PR DESCRIPTION
**Pull request by Immanuelolivia1**
Add unit tests for useScaffoldEventHistory #293

Test: tested for useScaffoldEventHistory hook

- [ ] Feature
- [ ] Bug
- [ ] Enhancement

### CODE REVIEW

**Comment by Immanuelolivia1** [comment]
@metalboyrick  I think there is an error in the useScaffoldEventHistory.ts file and because of that one of my test isn't passing  please can look into this.
 
Screenshot 2024-10-05 at 00 44 57

**Comment by metalboyrick** [comment]
Let me help you take a look

**Comment by metalboyrick** [comment]
Hi @Immanuelolivia1, I've verified the function based on your test case and seems that it's working fine. Kindly check the test case again. Thank you !

Maybe you can check the mocks and see if they are working as intended. I understand that mocks don't sometimes work properly (due to some wrong path resolution). 

I run this code with devnet and performed a transfer of Eth, it captured the event just fine.

image

One thing that may be an issue is that this is not mocked properly, you can try to mock from the import level and create your own `RpcProvider` mock implementation. 

image

Do not forget to test for the non-happy paths too!

Documentation (refer to it in case you need more context on what to test on): https://docs.scaffoldstark.com/hooks/useScaffoldEventHistory

Thank you so much for your help!

**Comment by metalboyrick** [comment]
Hi @Immanuelolivia1  , kindly remember that today is the last day of the ODHack. You can try my suggestions and let me know how those went!

**Comment by metalboyrick** [comment]
Hey @Immanuelolivia1, any updates on this?

**Comment by Immanuelolivia1** [comment]
Yes I'll make a PR soon almost done with it

**Comment by Immanuelolivia1** [comment]
Screenshot 2024-10-06 at 23 11 19
here is a screenshot of the coverage for the specific units i'm working on which is the useScaffoldEventHistory.

**Comment by Nadai2010** [comment]
Hi @Immanuelolivia1, I was reviewing your changes, please do not change the package.json or the rest of the files the coverage, or the rest of the tests, only the useScaffoldEventHistory.test.ts

To run the tests try

```bash
yarn test:nextjs run --coverage
```

Can you improve to 100?

imagen

**Comment by Immanuelolivia1** [comment]
Yeah sure I'll try, i thought i had no time left so i pushed what i have

**Comment by Nadai2010** [comment]
ODHack time ends today, but for the small ones and to be able to review and merge everything we have between tomorrow and Tuesday, upload the most important changes mentioned above, and if you can improve the test to 100% coverage that would be ideal. Thanks

**Comment by metalboyrick** [comment]
@Immanuelolivia1 @Nadai2010 70 - 80 is fine, but push to 100 if you can!

**Comment by metalboyrick** [comment]
Hey @Immanuelolivia1, any updates on this? ODHack is about to end.

**Comment by metalboyrick** [comment]
I think you can resolve @Nadai2010 's comments first then you'll be good.

> Hi @Immanuelolivia1, I was reviewing your changes, please do not change the package.json or the rest of the files the  coverage, or the rest of the tests, only the useScaffoldEventHistory.test.ts

**Review by metalboyrick — CHANGES_REQUESTED** [review]
I think you can resolve @Nadai2010 's comments first then you'll be good.

> Hi @Immanuelolivia1, I was reviewing your changes, please do not change the package.json or the rest of the files the  coverage, or the rest of the tests, only the useScaffoldEventHistory.test.ts

**Comment by Immanuelolivia1** [comment]
> I think you can resolve @Nadai2010 's comments first then you'll be good.
> 
> > Hi @Immanuelolivia1, I was reviewing your changes, please do not change the package.json or the rest of the files the  coverage, or the rest of the tests, only the useScaffoldEventHistory.test.ts

Screenshot 2024-10-07 at 22 52 01

I have tested for more cases and i have undone what i changed in the package.json file

**Review by Nadai2010 — CHANGES_REQUESTED** [review]
Sound good, please run correct format:

`yarn format` from fixed CI Jobs

**Comment by Nadai2010** [comment]
Hi @Immanuelolivia1, Still still failing the types formats, check the failures to be all green, ✅, try to check to run 

```bash
yarn next:check-types
```

And

```bash
yarn format
```

And resolve the recommendations

IMG_20241008_093147

**Comment by Immanuelolivia1** [comment]
> Hi @Immanuelolivia1, Still still failing the types formats, check the failures to be all green, ✅, try to check to run
> 
> ```shell
> yarn next:check-types
> ```
> 
> And
> 
> ```shell
> yarn format
> ```
> 
> And resolve the recommendations
> 
> IMG_20241008_093147

works fine on vscode but it keeps erroring once i push

**Comment by Nadai2010** [comment]
Hi @Immanuelolivia1 check fixed en CI

https://github.com/Scaffold-Stark/scaffold-stark-2/actions/runs/11236757470/job/31237586051

In this case

IMG_20241008_185505

**Review by metalboyrick — APPROVED** [review]
I will approve the changes for now, we will check this issue after OD as well

**Pull request closed without merging**
