### PR TITLE
test useTargetNetwork

### LINKED ISSUE #374: [TEST] Create unit tests for `useTargetNetwork.ts`
## Issue Overview

Unit tests required for the indicated file to ease future refactoring and feature validations.

## Proposed Solutions or Ideas (more like tips and reminders)

- We use vitest to run the unit tests, can refer to their documentation for the syntax: https://vitest.dev/, Jest developers shouldn't have too much of a hard time getting used to the syntax.
- Note that hooks testing tools are also now imported via `@testing-library/react`,
- Please refer to `README.md` on how to execute the tests
- Use `it.only()` to isolate tests in case you need to, but do not forget to remove it once you are submitting your PR.
- Mock when necessary. please make sure that the tests *NOT ONLY* works on your device
- If you're not sure of the features of the code unit to test, please refer to the [documentation](https://docs.scaffoldstark.com/hooks/), or free to ask on this issue page or on the Telegram Group

## Code Coverage
*IMPORTANT* - When submitting a PR, please provide a screenshot of the coverage for the specific units you are working on. We would like to achieve >= 70 % code coverage. 

Happy Hacking!

Example: 
image

### PR DESCRIPTION
**Pull request by Jemiiah**
# Task name here

Fixes #374

## Types of change

- [x] Test
- [ ] Bug
- [ ] Enhancement

## Comments (optional)
test result
Screenshot from 2024-12-17 11-19-17

### CODE REVIEW

**Comment by Nadai2010** [comment]
Hi @Jemiiah check the CI errors, run `yarn format` and leave everything green.

The coverage has been very good, we look forward to review by @metalboyrick 

imagen

**Review by metalboyrick — CHANGES_REQUESTED** [review]
same comments

**Review by Nadai2010 — COMMENTED** [review]
Hi @Jemiiah remember that you need to leave the CI green, check the `yarn format:check` and `yarn format` commands, otherwise it is ready for merging.

**Comment by Jemiiah** [comment]
Format worked

**Review by Nadai2010 — CHANGES_REQUESTED** [review]
Hi @Jemiiah, only commit the changes to useTargetNetwork.test.ts, not the rest of the file.

**Comment by Jemiiah** [comment]
> Hi @Jemiiah, only commit the changes to useTargetNetwork.test.ts, not the rest of the file.

The other commit are coming from the formating.

**Comment by Nadai2010** [comment]
You might have to sync with the main, but I don't think the rest of the files are the problem by format, @metalboyrick @Jemiiah

**Comment by metalboyrick** [comment]
hmm seems it still does not work, the merge

**Comment by metalboyrick** [comment]
@Jemiiah from your side, is it possible to pull main and merge to this branch?

**Review by metalboyrick — APPROVED** [review]
will fix formatting later

**Review by Nadai2010 — APPROVED** [review]

**Pull request merged**
