### PR TITLE
feat: Replace yarn deploy:reset with yarn deploy

### LINKED ISSUE #285: [CHORE] Replace `yarn deploy:reset` with `yarn deploy`, Create a `yarn deploy —no-reset`
## Issue Overview

We want to make the `yarn deploy:reset` behaviour the default one. Create a `yarn deploy —no-reset` if needed.

## Proposed Solutions or Ideas

- Update `package.json`

### PR DESCRIPTION
**Pull request by Jemiiah**
# Replaced yarn deploy:reset with yarn deploy, Created a yarn deploy —no-reset 
Fixes #285

## Types of change

- [ ] Feature
- [ ] Bug
- [ ] Enhancement

### CODE REVIEW

**Comment by Nadai2010** [comment]
Hi @Jemiiah , I think the idea is not what we wanted to do.

The `yarn deploy` should act like the `deploy:reset` works, that is, the `yarn deploy` will deploy new contracts replacing the previous ones in the deployments/chain_lastest.json and the `yarn deploy --no-reset` should deploy new contracts but without replacing or resetting the previous ones (the old ones will remain as deployments/chain_1892739817.json) and the new ones deployed will be in deployments/chain_lastest.json

I'm right @jrcarlos2000 ??

Adjust the scripts so that it works like this

**Comment by 0xquantum3labs** [comment]
> Hi @Jemiiah , I think the idea is not what we wanted to do.
> 
> The `yarn deploy` should act like the `deploy:reset` works, that is, the `yarn deploy` will deploy new contracts replacing the previous ones in the deployments/chain_lastest.json and the `yarn deploy --no-reset` should deploy new contracts but without replacing or resetting the previous ones (the old ones will remain as deployments/chain_1892739817.json) and the new ones deployed will be in deployments/chain_lastest.json
> 
> I'm right @jrcarlos2000 ??
> 
> Adjust the scripts so that it works like this

correct this is the idea @Jemiiah @Nadai2010 @metalboyrick

**Review by 0xquantum3labs — CHANGES_REQUESTED** [review]

**Comment by metalboyrick** [comment]
Hey @Jemiiah, any updates on this?

**Comment by Nadai2010** [comment]
Hi @Jemiiah, the ODHack is about to end, please upload your latest changes as soon as possible, thanks

**Comment by Jemiiah** [comment]
thank you for reopening ill be pushing in the changes shortly

**Comment by Jemiiah** [comment]
I have made deploy to act as deploy:reset by default and also added a deploy:no-reset

I left the deploy:reset for backwards compatibility, let me know if I should remove it.

**Review by Nadai2010 — APPROVED** [review]

**Comment by 0xquantum3labs** [comment]
closing this for now as there are some hiccups in the implementation

**Pull request closed without merging**
